spring.application.name=Assignment5
server.port=2000
logging.level.org.hibernate=INFO
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=LOCAL_ORCDB
spring.datasource.password=LOCAL_ORCDB
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.transaction.coordinator_class=jdbc
spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
