spring.application.name=Assignment7-Multipart_Upload1
server.port=2000
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=LOCAL_ORCDB
spring.datasource.password=LOCAL_ORCDB
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
# Maximum file size
spring.servlet.multipart.max-file-size=10MB

# Maximum request size (includes all files and form data)
spring.servlet.multipart.max-request-size=10MB