spring.application.name=Assignment8-Multipart_Download1
server.port=2000

#Swagger Configuration
# Enable or disable Swagger UI
springdoc.swagger-ui.enabled=true

# API docs path (OpenAPI JSON)
springdoc.api-docs.path=/v3/api-docs

# Customize title or description (using application info)
#springdoc.swagger-ui.title=Multipart File Upload 2
#springdoc.swagger-ui.description=API documentation for Files Reading Multipart API

# Sort endpoints alphabetically
springdoc.swagger-ui.operationsSorter=alpha

# Sort tags alphabetically
springdoc.swagger-ui.tagsSorter=alpha

# Display request duration
springdoc.swagger-ui.displayRequestDuration=true

# Custom path for Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
